#!/bin/bash
export MONGO_URL='mongodb://127.0.0.1:27017/wekan'
export ROOT_URL='https://192.168.0.121'
export MAIL_FROM='wekan-admin@localhost'
export PORT=8080
cd /home/wekan/wekan-0.10.1/bundle/
node main.js
